### ISSUE TITLE
VTB补

### ISSUE THREAD

**Issue by 123heheheabc** [dd-center/vdb#233] opened 2020-04-14 10:09 UTC
建议首先参考 [这里](https://github.com/dd-center/vdb/issues/113#issuecomment-560273409) 来确定要添加的用户确实符合 VTB 标准

幻想乡の鬼狐狸
https://space.bilibili.com/535637/
加加Official
https://space.bilibili.com/1506609/
晓晨Official
https://space.bilibili.com/3456630/
还有醒着的么
https://space.bilibili.com/2100679/
白猫永远不打烊
https://space.bilibili.com/5772351/
みやぢmiyadi
https://space.bilibili.com/418325861/
星川杏_Channel
https://space.bilibili.com/1384726/
神楽唯Official
https://space.bilibili.com/38631/
バクの良Official
https://space.bilibili.com/550611/
房日兔Official
https://space.bilibili.com/314422248/
喀什罗蒂Official
https://space.bilibili.com/19461407/
comdost
https://space.bilibili.com/416804826/
白羽八shiroha
https://space.bilibili.com/4621148/
苏了个妹
https://space.bilibili.com/5963844/

**Comment by simon300000** [comment] 2020-04-17 20:56
Duplicate of #201

**Closed by simon300000** 2020-04-17 20:56 UTC
